### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/generic-shooter-game#1]
# Motivation
Set up basic requirements for getting the app off the ground.

# Tasks
- [x] Learn how to use Koa.
- [x] Add aliases for linking module aliases.
- [x] Get a basic example up and running.
