### ISSUE TITLE
User can see a connected Canvas

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/generic-shooter-game#3]
# Motivation
We want to be able to see a screen that recieves input from socket.io and feeds back the computed information.

# Tasks
- [ ] Be able to see a canvas.
- [ ] Connect front and backends with socket.io.
- [ ] Be able to send information to the backend with socket io.
- [ ] Be able to recieve information to the frontend with socket.io.
